name: Build release candidate version and release it

on:
  push:
    tags:
      - '!.*v[0-9]+\.[0-9]+\.[0-9]+.*'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc'
      - 'v[0-9]+\.[0-9]+\.[0-9]+-rc\.[0-9]+'

jobs:
  build:
    strategy:
      matrix:
        # Use these Python versions
        python: [
          3.11.1,     # Current latest Python
        ]
        # and run only on macOS
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Show Python version
        run: python --version
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Pack MCDR Plugin
        run: python pack.py
      - name: Get Tag
        uses: mad9000/actions-find-and-replace-string@3
        id: gettag
        with:
          source: ${{ github.ref }}
          find: 'refs/tags/'
          replace: ''
      - name: Get Version Number
        uses: mad9000/actions-find-and-replace-string@3
        id: getversion
        with:
          source: ${{ steps.gettag.outputs.value }}
          find: 'v'
          replace: ''
      - name: Get Version (RC with numeric identifiers)
        uses: frabert/replace-string-action@v2.4
        id: getversion-rc
        with:
          string: ${{ steps.getversion.outputs.value }}
          pattern: '-rc\.'
          replace-with: ' Release Candidate '
      - name: Get Version (RC without numeric identifiers)
        uses: frabert/replace-string-action@v2.4
        id: getversion-rc-no-numeric
        with:
          string: ${{ steps.getversion-rc.outputs.replaced }}
          pattern: '-rc'
          replace-with: ' Release Candidate'
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: SHA to upper case
        id: sha
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.SHORT_SHA }}
      - name: Release
        uses: ncipollo/release-action@v1.12.0
        with:
          token: ${{ secrets.GH_TOKEN }}
          name: "Version ${{ steps.getversion-rc-no-numeric.outputs.replaced }} (${{ steps.sha.outputs.uppercase }})"
          artifacts: "build/distributions/*.mcdr"
          bodyFile: "RELEASE_NOTE.md"
          prerelease: true
