name: Build dev version artifacts
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        # Use these Python versions
        python: [
          3.11.1,     # Current latest Python
        ]
        # and run on Linux, macOS, and Windows
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Show Python version
        run: python --version
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt
      - name: Pack MCDR Plugin
        run: python pack.py
      - name: Get short SHA
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
      - name: Upload Artifacts
        if: ${{ runner.os == 'macOS' }} # Only upload artifacts built on macOS
        uses: actions/upload-artifact@v4
        with:
          name: RemoteMC-MCDR-${{ env.SHORT_SHA }}
          path: build/distributions
